### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by stefanisandridge** [NYU-DevOps-Inventory-Team/inventories#1]
**As a** developer
**I need** a dedicated Vagrant environment
**So that** I can build and test the inventory microservice 

**Assumptions:**

- A `vagrantfile` has been created in the repo
- The development environment will include all necessary software (Python, Flask)
- Will use Vagrant and VirtualBox to spin up a local development environment

**Acceptance Criteria:**

**Given** that I have a repository of code including a `vagrantfile`
**When** I run a `vagrant up` command
**Then** I have a complete development environment running on my virtual machine

**Comment by jrose023** [comment]
@aganeesh @marina2232 @neeharikatummala @stefanisandridge the necessary files to complete this issue on each of your own individual machines is now pushed. go ahead an run a git pull and try running a vagrant up

**Comment by stefanisandridge** [comment]
Development environment is set up. Closing.
