### ISSUE TITLE
Create a vagrantfile

### ISSUE THREAD

**Issue by jrose023** [NYU-DevOps-Inventory-Team/inventories#5]
**As a** developer
**I need** a `vagrantfile`
**So that** my vagrant environment will start properly

**Assumptions:**

* I have a template for a vagrant file containing all necessary software to be provisioned
* I have a repo in which to put my `vagrantfile`

**Acceptance Criteria:**

**Given** I have created the `vagrantfile` and placed it in project repo
**When** I run the command `vagrant up`
**Then** the vagrant environment starts properly

**Comment by stefanisandridge** [comment]
Reviewed and approved, closing
