### ISSUE TITLE
Delete inventory product

### ISSUE THREAD

**Issue by jrose023** [NYU-DevOps-Inventory-Team/inventories#7]
**As an** inventory/warehouse manager
**I need** to be able to remove product from inventory
**So that** I can accurately track inventory and so the database is concise

**Assumptions:**

- The product exists/has already been created in the inventory resource
- There only reason for deleting an inventory value is that we are no longer selling that item
- The endpoint will only handle deletion of one product

**Acceptance Criteria:**

**Given** that I have an endpoint for a deleting a product from inventory
**When** I issue a DELETE request 
**Then** the product and associated attributes are removed from the inventory

**Comment by stefanisandridge** [comment]
Adding 'Enhancement' label to the CRUD stories.
