### ISSUE TITLE
Create a Product in Inventory data model

### ISSUE THREAD

**Issue by jrose023** [NYU-DevOps-Inventory-Team/inventories#9]
**As a** developer
**I need** a fixed data model of attributes of a product in inventory
**So that** I can build the inventory API consistently

**Assumptions:**

* There is a known list of attributes a product can have
* Follows best naming conventions for an API
* I have a database to apply this data model

**Acceptance Criteria:**

**When** I create my API
**Then** There will be a defined way to display the display of products (what attributes to show, sorting, etc.)

**Comment by jrose023** [comment]
![image.png](https://images.zenhubusercontent.com/602db290a7944e3fa083856b/f25b1ead-c81a-4e07-8653-ae09dc2a0f65)

**Comment by aganeesh** [comment]
* Models video
* Need to put our attributes in table_schema, also nullable=false for required ones
* Put the same attributes under serialize -> return, same fo deserialize (self.attribute), no id in deserialize to avoid deserialize the primary key
* Go to test models py
* Steal from test pets
    * Copy 34-36 and put at line 10 test models
    * 44-63 copy, paste in place of 20-36
    * Type on line 9 from ‘’’’’’service import app’’’’’’’
    * Change pet to account or whatever we used
* Go to lab flask rest requirements and take line 5, paste as line 6 in our requirements file
* pip install -r requirements.txt
* Take line 77 from his Vagrantfile and put it in yours at 76, probably done already in ours
* Commit/push
